#!/bin/bash
#==========================================
#Ip Sorter
#Name: ipsorter
#Written by: Darren Seabrook - Jan 2017
#Purpose: Find all IPs generating "authenication failture" message, extract their IPs and count the unique IPs.
#==========================================

#make a directory called "ips"
mkdir -p ips

#remove files in folder "ips"
rm -f ips/*.txt

# Sort: Get all with "Auth failure", then pull out IPs, sort it, count uniques, sort again, get top 10 IPs
grep -e "Authentication failure" /home/common/warn* | grep -h -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'| sort | uniq -c | sort -nr | head -n10 > top10

# Print contents of top10, pipe into while loop
awk '{print}' top10 | while read o i; do

# ipinfo kept cutting the connection, so need to keep trying:
while [ 1 ]; do
wget -O ips/$i.txt http://ipinfo.io/$i --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0 --continue 2>null
    if [ $? = 0 ]; then break; fi; # check return value, break if successful (0)
    sleep 1s;
done

#Find the country names of the IP addresses:
country=$(grep -Po '(?<="country": ")[^"]*' ips/$i.txt)

# Sort top 10 ips by frequency, highest to lowest
echo $o $i $country >> 10_before_freq_sort

done;
cat 10_before_freq_sort | sort -nr

echo done!
